project_name: "radar-ecg"
data_dir: "dataset_processed"
unprocessed_data_dir: "dataset"
save_dir: "outputs"
api_key: ""

model: TCN
input_size: 1
output_size: 1
hidden_size: 200
signal_length: 2954
frame_time: 0.01015455
num_layers: 11
kernel_size: 3

max_epochs: 1
batch_size: 8
learning_rate: 1e-3
model_path: ""

dev_mode: False
test_only: False


