wandb:
  project_name: "radar-ecg-results"
  api_key: "48fd3e4aefe699d5db6a9025aa409e684338a4f5"

dirs:
  data_dir: "dataset_processed"
  unprocessed_data_dir: "dataset"
  save_dir: "outputs"

model: TCN # LSTM, GRU, RNN, MLP, TCN

models:
  TCN:
    run_name: "test_1d_regression"
    input_size: 1 # 1, 130
    output_size: 1 # 1, 2
    hidden_size: 200
    num_layers: 8 # 11 (leads to receptive field of 4095 for 30s slices), 8 (leads to receptive field of 511 for 5s slices)
    kernel_size: 3

  LSTM:
    run_name: "_test_1d_regression"
    input_size: 130
    output_size: 2
    hidden_size: 10
    num_layers: 2
    kernel_size: 0

  GRU:
    run_name: "_test_1d_regression"
    input_size: 130
    output_size: 2
    hidden_size: 200
    num_layers: 2
    kernel_size: 0

  RNN:
    run_name: "_test_1d_regression"
    input_size: 130
    output_size: 2
    hidden_size: 10
    num_layers: 2
    kernel_size: 0

preprocessing:
  multi_dim: False
  mode: "sawtooth" # "sawtooth", "binary classification"
  slice_duration: 5 # 5, 30 (seconds)

training:
  max_epochs: 1
  batch_size: 8
  learning_rate: 1e-3
  dev_mode: False

inference:
  model_path: ""

testing:
  plot: True
  prominence: 0.2
  wandb_log: True

main:
    mode: "full" # "train", "test", "full", "leave_one_out"




