wandb:
  project_name: "radar-ecg-results"
  api_key: ""

dirs:
  data_dir: "dataset_processed"
  unprocessed_data_dir: "dataset"
  save_dir: "outputs"

data:
  signal_length: 2954
  frame_time: 0.01015455

model: LSTM # LSTM, GRU, RNN, MLP, TCN

models:
  TCN:
    run_name: ""
    input_size: 1 # 1, 130
    output_size: 1 # 1, 2
    hidden_size: 200
    num_layers: 11
    kernel_size: 3

  LSTM:
    run_name: "_test_1d_regression"
    input_size: 130
    output_size: 2
    hidden_size: 200
    num_layers: 2
    kernel_size: 0

  GRU:
    run_name: "_test_1d_regression"
    input_size: 130
    output_size: 2
    hidden_size: 200
    num_layers: 2
    kernel_size: 0

  RNN:
    run_name: "_test_1d_regression"
    input_size: 130
    output_size: 2
    hidden_size: 200
    num_layers: 2
    kernel_size: 0

preprocessing:
  multi_dim: True
  mode: "sawtooth" # "sawtooth", "binary classification"

training:
  max_epochs: 100
  batch_size: 8
  learning_rate: 1e-3
  dev_mode: True

inference:
  model_path: ""

testing:
  plot: True
  prominence: 0.7
  wandb_log: True

main:
    mode: "train" # "train", "test", "full", "leave_one_out"




