project_name: "radar-ecg"
data_dir: "dataset_processed"
unprocessed_data_dir: "dataset"
save_dir: "outputs"
api_key: ""

model: TCN
input_size: 65
output_size: 1
hidden_size: 200
num_layers: 11
kernel_size: 3

max_epochs: 200
batch_size: 8
learning_rate: 1e-3
model_path: ""

dev_mode: True
test_only: False


